# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Solstice/Documents/eSnyne_WorkSpace/eSnyne 1.1/eSnyne 1.1.srcs/sources_1/bd/eSnyne_core/ip/eSnyne_core_processing_system7_0_0/eSnyne_core_processing_system7_0_0.xci
# IP: The module: 'eSnyne_core_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Solstice/Documents/eSnyne_WorkSpace/eSnyne 1.1/eSnyne 1.1.gen/sources_1/bd/eSnyne_core/ip/eSnyne_core_processing_system7_0_0/eSnyne_core_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'eSnyne_core_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Solstice/Documents/eSnyne_WorkSpace/eSnyne 1.1/eSnyne 1.1.srcs/sources_1/bd/eSnyne_core/ip/eSnyne_core_processing_system7_0_0/eSnyne_core_processing_system7_0_0.xci
# IP: The module: 'eSnyne_core_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Solstice/Documents/eSnyne_WorkSpace/eSnyne 1.1/eSnyne 1.1.gen/sources_1/bd/eSnyne_core/ip/eSnyne_core_processing_system7_0_0/eSnyne_core_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'eSnyne_core_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
