# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# Block Designs: bd/eSnyne_core/eSnyne_core.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eSnyne_core || ORIG_REF_NAME==eSnyne_core} -quiet] -quiet

# IP: bd/eSnyne_core/ip/eSnyne_core_processing_system7_0_0/eSnyne_core_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==eSnyne_core_processing_system7_0_0 || ORIG_REF_NAME==eSnyne_core_processing_system7_0_0} -quiet] -quiet

# XDC: c:/Users/Solstice/Documents/eSnyne_WorkSpace/eSnyne 1.1/eSnyne 1.1.gen/sources_1/bd/eSnyne_core/eSnyne_core_ooc.xdc
